#!/bin/bash

require() {
  for prog in "${@}"
  do
    if ! which "$prog" >/dev/null
    then
     echo "'$prog' required but not present." >&2
     return 1
    fi
  done
}

check_sudo() {
  if ! sudo -n true
  then
    echo "'sudo' not configured to run passwordless!" >&2 
    return 1
  fi
}

install_scriptlet() {
  if ! require basename dirname
  then
    echo "Prerequisites to install are missing, install not done.">&2
    return 1
  fi
  dir="$(basename "$(dirname "$0")")"
  if [ "$dir" == 'available' ]
  then
    echo "Installing $(basename "$0")"
    ln -sf "../available/$(basename "$0")" "$(dirname "$(dirname "$0")")/enabled/$(basename "$0")"
  fi
}

validate() {
  if prereq
  then
    echo "Prerequisites are met"
    exit 0
  else
    echo "Prequisites are missing!" >&2
    exit 1
  fi
}

parse_args() {
  unset MODE
  unset RESTARTED
  unset REMOTE
  while [ $# -gt 0 ]
  do
    case "$1" in
    -a|--all)
      REMOTE=1
      shift
      ;;
    -i|--install)
      MODE=install
      shift
      ;;
    -m|--modified)
      RESTARTED=1
      shift
      ;;
    -u|--update)
      MODE=update
      shift
      ;;
    -v|--validate)
      MODE=validate
      shift
      ;;
    *)
      shift
    esac
  done
  export MODE RESTARTED REMOTE
}
