#!/bin/bash

cd "$(dirname "$0")"
. ./libupd

require git && git pull

echo
echo ================== Starting $(whoami)@$(hostname) ================== 
DIR="$(dirname "$0")"
for ITEM in $(ls "$DIR"/enabled/* | sort)
do
  $ITEM --update
done
echo ================== Finished $(whoami)@$(hostname) ================== 

