#!/bin/bash

cd "$(dirname "$0")"
. ./libupd

require git && git pull

echo
echo ================== Starting $(whoami)@$(hostname) ================== 
for ITEM in $(ls enabled/* | sort)
do
  $ITEM --update
done
echo ================== Finished $(whoami)@$(hostname) ================== 

