#!/bin/bash

. "$(dirname "$0")/../libupd"

prereq() {
  check_sudo && require apt-get
}

install() {
  require apt-get || ( echo "apt-get not found, not installing $(basename "$0")" >&2; return 1 )
  require sudo || ( echo "sudo not found, not installing $(basename "$0")" >&2; return 1 )

  install_scriptlet
}

update() {
  echo ------ Starting apt-get ------
  prereq || return 1

  sudo apt-get update
  sudo apt-get -y full-upgrade
  sudo apt-get -y autoremove

  if [ -e /var/run/reboot-required ]
  then
    if [ -e /var/run/reboot-required.pkgs ]
    then
      echo "Restart required due to the following packages:"
      sed -e 's/^/  * /' /var/run/reboot-required.pkgs
    else
      echo "Restart required due to unspecified packages."
    fi
  else
    echo "No reboot required."
  fi
}

parse_args "${@}"
echo MODE=${MODE}
case "$MODE" in 
  install)
    install
    exit
    ;;
  update)
    update
    exit
    ;;
  validate)
    validate
    exit
    ;;
  *)
    echo "Usage: $(basename $0) -i|--install|-v|--validate|-u|--update"
    echo "Called as: $0 ${@}"
    exit 1
esac
