#!/bin/bash

. "$(dirname "$0")/../libupd"

prereq() {
  check_sudo && require rnutil
}

install() {
  if ! require sudo
  then
    echo "sudo not found, not installing $(basename "$0")" >&2
    return 1
  fi
  if ! require rnutil
  then
    echo "Not on Netgear NAS, not installing $(basename "$0")" >&2
    return 1
  fi
  install_scriptlet
}

update() {
  echo ------ Starting netgear-nas ------
  prereq || return 1
  sudo rnutil firmware_update
}

parse_args "${@}"
echo MODE=${MODE}
case "$MODE" in 
  install)
    install
    exit
    ;;
  update)
    update
    exit
    ;;
  validate)
    validate
    exit
    ;;
  *)
    echo "Usage: $(basename $0) -i|--install|-v|--validate|-u|--update"
    echo "Called as: $0 ${@}"
    exit 1
esac
