#!/bin/bash

. "$(dirname "$0")/../libupd"

prereq() {
  check_sudo
  require snap
}

install() {
  require snap || ( echo "snap not found, not installing $(basename "$0")" >&2; return 1 )
  install_scriptlet
}

update() {
  echo ------ Starting snap ------
  prereq || return 1
  sudo snap refresh
}

parse_args
case "$MODE" in 
  install)
    install
    exit
    ;;
  update)
    update
    exit
    ;;
  validate)
    validate
    exit
    ;;
  *)
    echo "Usage: $(basename $0) -i|--install|-v|--validate|-u|--update"
    echo "Called as: $0 ${@}"
    exit 1
esac
