#!/bin/bash

. "$(dirname "$0")/../libupd"

prereq() {
  check_sudo
  require fwupdmgr
}

install() {
  require fwupdmgr || ( echo "fwupdmgr not found, not installing $(basename "$0")" >&2; return 1 )
  install_scriptlet
}

update () {
  echo ------ Starting firmware ------
  if sudo systemctl status fwupd &>/dev/null
  then
    echo "Updating firmware"
    sudo fwupdmgr refresh --force
    sudo fwupdmgr update -y
  else
    echo "fwupdmgr not running?" >&2
    return 1
  fi
}

MODE="$(parse_args)"
case "$MODE" in 
  install)
    install
    exit
    ;;
  update)
    update
    exit
    ;;
  validate)
    validate
    exit
    ;;
  *)
    echo "Usage: $(basename $0) -i|--install|-v|--validate|-u|--update"
    echo "Called as: $0 ${@}"
    exit 1
esac
