#!/bin/bash

. "$(dirname "$0")/../libupd"

prereq() {
  require /usr/games/steamcmd
}

install() {
  require /usr/games/steamcmd || ( echo "steamcmd not found, not installing $(basename "$0")" >&2; return 1 )
  install_scriptlet
}

update () {
  echo ------ Starting firmware ------
  prereq || return 1
  /usr/games/steamcmd +login anonymous +app_update +quit
}

case "$1" in
  -i|--install)
    install
    exit
    ;;
  -v|--validate)
    if prereq
    then
      echo "Prerequisites are met"
      exit 0
    else
      echo "Prequisites are missing!" >&2
      exit 1
    fi
    ;;
  -u|--update)
    update
    exit
    ;;
  *)
    echo "Usage: $(basename $0) -i|--install|-v|--validate|-u|--update"
    exit 1
esac
