#!/bin/bash

. "$(dirname "$0")/../libupd"

prereq() {
  require /usr/games/steamcmd
}

install() {
  require /usr/games/steamcmd || ( echo "steamcmd not found, not installing $(basename "$0")" >&2; return 1 )
  install_scriptlet
}

update () {
  echo ------ Starting firmware ------
  prereq || return 1
  /usr/games/steamcmd +login anonymous +app_update +quit
}

parse_args
case "$MODE" in 
  install)
    install
    exit
    ;;
  update)
    update
    exit
    ;;
  validate)
    validate
    exit
    ;;
  *)
    echo "Usage: $(basename $0) -i|--install|-v|--validate|-u|--update"
    echo "Called as: $0 ${@}"
    exit 1
esac
