#!/bin/bash

. "$(dirname "$0")/../libupd"

prereq() {
  require /usr/local/bin/oh-my-posh
}

install() {
  if ! require /usr/local/bin/oh-my-posh
  then
    echo "oh-my-posh not found, not installing $(basename "$0")" >&2
    return 1
  fi
  install_scriptlet
}

update() {
  echo ------ Starting oh-my-posh  ------
  prereq || return 1
  if ! oh-my-posh notice
  then
    curl -s https://ohmyposh.dev/install.sh | sudo bash -s
  fi
}

parse_args "${@}"
case "$MODE" in
  install)
    install
    exit;
    ;;
  update)
    update
    exit
    ;;
  *)
    echo "Usage: $(basename $0) -i|--install|-v|--validate|-u|--update"
    echo "Called as: $0 ${@}"
    exit 1
esac

